# Trajectory Visualization (per-seed GIF)

data:
  dataset_dir: "/data3/vla-reasoning/dataset/bench2drive220_confounded"

seed:
  route_id: 2416
  seed_id: 200

processing:
  frame_step: 1
  max_frames: 99999
  # resize: { width: 640, height: 360 }  # optional; remove or set nulls to keep original

output:
  out_dir: "/home/vla-reasoning/proj/vlm-gabril/Grounded-SAM-2/bench2drive_processor/refactor"
  gif_name: "{seed_id}_traj.gif"
  fps: 20
