# Hydra configuration for Behavior Cloning with Confounded Dataset
# Inherits from train_bc.yaml and overrides specific parameters

defaults:
  - train_bc
  - _self_

# Override data configuration for confounded dataset
data:
  hdf5_path: "/data3/vla-reasoning/dataset/bench2drive220_robomimic_confounded.hdf5"
  gaze_key: "gaze_coords_filter_dynamic"
  num_episodes: 200
  batch_size: 1000
  cache_mode: "all"

# Override gaze configuration
gaze:
  method: "Reg"
  mask_sigma: 20.0

# Override dropout configuration  
dropout:
  method: "None"

# Override training configuration
training:
  epochs: 200
  use_amp: true
  use_compile: true
  device: "cuda:0"
# Override scheduler configuration
scheduler:
  type: "step"
  step_size: 50
