# Hydra configuration for Behavior Cloning with Confounded Dataset
# Inherits from train_bc_base.yaml and overrides specific parameters

defaults:
  - train_bc_base
  - _self_

# Override data configuration for confounded dataset
data:
  hdf5_path: "/data3/vla-reasoning/dataset/bench2drive220_robomimic.hdf5"
  gaze_key: "gaze_coords"
  num_episodes: 200
  batch_size: 2000
  cache_mode: "all"

# Override gaze configuration
gaze:
  method: "Reg"
  mask_sigma: 30.0

# Override dropout configuration  
dropout:
  method: "None"

# Override training configuration
training:
  epochs: 500
  use_amp: true
  use_compile: true
  device: "cuda:0"
# Override scheduler configuration
scheduler:
  type: "step"
  step_size: 50
